version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.11
    container_name: gozero-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=default
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=default=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data

  redis:
    image: redis:7.2
    container_name: gozero-redis
    ports:
      - "6479:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: xin000000
      MYSQL_DATABASE: zero
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3310:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: gozero-mongodb
    ports:
      - "37017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: xin-im
    volumes:
      - mongodb-data:/data/db

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: gozero-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.6
    container_name: gozero-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.21.5:9092 # 这里需要使用宿主机
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/bitnami/kafka

#  apisix:
#    image: apache/apisix:3.10.0-debian
#    container_name: gozero-apisix
#    depends_on:
#      - etcd
#    environment:
#      - APISIX_CONFIG_ETCD_HOST=http://etcd:2379
#    volumes:
#      - ./conf/apisix_config.yaml:/usr/local/apisix/conf/config.yaml:ro
#      - ./wait-for-it.sh:/wait-for-it.sh
#    ports:
#      - "9080:9080"
#      - "9443:9443"
#      - "9091:9091"
#    restart: always
#
#  apisix-dashboard:
#    image: apache/apisix-dashboard:3.0.1-alpine
#    container_name: gozero-apisix-dashboard
#    depends_on:
#      - etcd
#    ports:
#      - "9010:9000"
#    environment:
#      - RUN_MODE=release
#      - ETCD_ENDPOINTS=http://etcd:2379
#    volumes:
#      - ./conf/apisix_dashboard_conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
#    restart: always

  sail:
    image: ccr.ccs.tencentyun.com/hyy-yu/sail:latest
    ports:
      - "8108:8108"
    volumes:
      - "./conf/compose-cfg.toml:/app/cfg.toml"
    restart: always

volumes:
  etcd-data:
  redis-data:
  mysql-data:
  mongodb-data:
  kafka-data:
  zookeeper-data:
